### ISSUE TITLE
It seems key with the TTL is often removed earlier than specified.

### ISSUE THREAD

**Issue by Alesh** [evilsocket/gibson#9]
It seems key with the TTL is often removed earlier than specified. This can happen in 200-900 milliseconds earlier than necessary.  I noticed this when I wrote tests for my python client. This is illustrated by script https://github.com/AleshGood/pyGibson/blob/dev/testsuite/bugtest_ttl.py.

``` bash
# uname -a
Linux x4desktop 3.2.0-48-generic #74-Ubuntu SMP Thu Jun 6 19:43:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by evilsocket** [comment]
item eta is computed using the server timer ( updated on every event loop ), so it could be not perfectly synchronized with the client timer.
gonna fix this evening :)

Tnx

**Comment by evilsocket** [comment]
It came out that this is not a Gibson bug ... millisecond precision sleeps actually ( consider the parsing and execution overhead ) takes longer than the actual delay, for instance ( i've tried with a test in PHP ), i have results of total waited time ranging from 2.9 to 3.1 ( 30 loops of 0.1s ), so since the Gibson timer is highly accurate, it may occur that two timers are not synchronized.

I'm closing this, feel free to comment to add comments, i will reopen the issue if needed.
